version: '3.8'

services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: jdbc-sample
    ports:
      - "3306:3306"